language: php
php: 
    - '5.6'
    
branches:
    only: new-branch
    
before_install:
  - composer self-update
    
before_script:
  - composer install --no-interaction
        
script:
    - composer test
    
