language: php
php: 
    - '7.1'
    
branches:
    only: new-branch
    
before_script: 
    - composer self-update
    -composer install -prefer-source --no-interaction --dev
    
script: phpunit
    
        
